# Generated by Django 4.1.5 on 2023-03-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_f_ile_project_uploaded_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='uploaded_file',
            new_name='uploadedFile',
        ),
    ]
