# Generated by Django 4.1.5 on 2023-03-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_uploaded_file_project_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='uploadedFile',
            new_name='uploaded',
        ),
    ]
