# Generated by Django 4.1.5 on 2023-02-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_customer_employees_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_employees',
            name='user_permission',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier_employees',
            name='user_permission',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
